/** @type {import('tailwindcss').Config} */
const colors = require("tailwindcss/colors");
export default {
    content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx,vue}", "./src/views/**/*.{js,ts,jsx,tsx,vue}"],
    safelist: ["col-span-1", "col-span-2", "col-span-3", "col-span-4", "col-span-5", "md:col-span-1", "md:col-span-2", "md:col-span-3", "md:col-span-4", "md:col-span-5"],
    theme: {
        extend: {},
        textColor: (theme) => theme("colors"),
        textOpacity: (theme) => theme("opacity"),
        screens: {
            sm: "576px",
            md: "769px",
            lg: "992px",
            xl: "1280px",
            "2xl": "1400px",
            "3xl": "1600px",
        },
        colors: {
            transparent: "transparent",
            current: "currentColor",
            white: colors.white,
            red: {
                50: "#ead7d7",
                100: "#FFE9EB", // background
                200: "#ea9f9f",
                300: "#FFA7A7", // border
                400: "#ea6768",
                500: "#FE4F52", // icon
                600: "#FF3550",
                700: "#c73949",
                800: "#ad3240",
                900: "#8a2833",
            },
            yellow: {
                50: "#FFFCEA",
                100: "#FEF5D7",
                200: "#FEF0C0",
                300: "#FDECAA",
                400: "#FDE894",
                500: "#FCE47F",
                600: "#FCE06A",
                700: "#FCDC54",
                800: "#FBD83A",
                900: "#FFCA00",
            },
            orange: {
                50: "#ffefdb",
                100: "#ffe6c7",
                200: "#ffd5a1",
                300: "#ffbc69",
                400: "#ffaf4d",
                500: "#FAA134",
                600: "#ff5733",
                700: "#d17400",
                800: "#b36300",
                900: "#8f4f00",
            },
            green: {
                100: "#E8F5E9", // background
                200: "#B3FFD9",
                300: "#ABE8D1", // border
                400: "#66FFB3",
                500: "#2DC58C", // icon
                600: "#24B354",
                700: "#1F9948",
                800: "#156630",
                900: "#104D24",
            },
            blue: {
                50: "#f2f2f2",
                100: "#eaeef2",
                200: "#d3e2f2",
                300: "#accff2",
                400: "#8cbff2",
                500: "#4DB3E5",
                600: "#51AAF8",
                700: "#1F86E3",
                800: "#3071ab",
                900: "#265987",
            },
            purple: {
                50: "#f2f2f2",
                100: "#eaeef2",
                200: "#B2ADF0",
                300: "#9890F0",
                400: "#8378F0",
                500: "#1C4BDB",
                600: "#4A3DCC",
                700: "#291F99",
                800: "#160D80",
                900: "#0A0073",
            },
            gray: {
                100: "#F5F5F5",
                200: "#F1F1F1",
                300: "#EAEAEB",
                400: "#E6E6E7",
                500: "#E0E1E2",
                600: "#DCDDDE",
                700: "#D7D8D9",
                800: "#D2D4D5",
                900: "#D1D3D4",
            },
            black: {
                100: "#D7D8D9",
                200: "#BFC1C3",
                300: "#A8AAAD",
                400: "#939498",
                500: "#7E8083",
                600: "#6C6D70",
                700: "#57595B",
                800: "#333333",
                900: "#000000",
            },
        },
        spacing: {
            px: "1px",
            0: "0px",
            0.5: "0.125rem",
            1: "0.25rem",
            1.5: "0.375rem",
            2: "0.5rem",
            2.5: "0.625rem",
            3: "0.75rem",
            3.5: "0.875rem",
            4: "1rem",
            5: "1.25rem",
            6: "1.5rem",
            7: "1.75rem",
            8: "2rem",
            9: "2.25rem",
            10: "2.5rem",
            11: "2.75rem",
            12: "3rem",
            14: "3.5rem",
            16: "4rem",
            20: "5rem",
            24: "6rem",
            28: "7rem",
            32: "8rem",
            36: "9rem",
            40: "10rem",
            44: "11rem",
            48: "12rem",
            52: "13rem",
            56: "14rem",
            60: "15rem",
            64: "16rem",
            72: "18rem",
            80: "20rem",
            96: "24rem",
            "5%": "5%",
            "10%": "10%",
            "15%": "15%",
            "20%": "20%",
            "25%": "25%",
            "75%": "75%",
            "80%": "80%",
            "85%": "85%",
            "90%": "90%",
            header: "120px",
            headerMb: "80px",
            header2: "72px",
        },
        boxShadow: {
            sm: "0 1px 2px 0 rgba(0, 0, 0, 0.05)",
            DEFAULT: "0 1px 3px 0 rgba(0, 0, 0, 0.1), 0 1px 2px 0 rgba(0, 0, 0, 0.06)",
            md: "0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06)",
            lg: "0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -2px rgba(0, 0, 0, 0.05)",
            xl: "0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04)",
            "2xl": "0 25px 50px -12px rgba(0, 0, 0, 0.25)",
            inner: "inset 0 2px 4px 0 rgba(0, 0, 0, 0.06)",
            formDefault: "inset 0 -1px 0 0px #D9D9D9",
            formFocus: "inset 0 -2px 0 0px #FFCC00",
            header: "0 4px 6px rgba(0,0,0,.07)",
            footer: "5px -1px 6px 0 rgba(2,43,30,.13)",
            none: "none",
        },
        container: {
            center: true,
            padding: {
                DEFAULT: "1.5rem",
                lg: "3rem",
                xl: "5rem",
                "2xl": "6rem",
                "3xl": "8rem",
            },
        },
    },
    variants: {
        accessibility: ["responsive", "focus-within", "focus"],
        alignContent: ["responsive"],
        alignItems: ["responsive"],
        alignSelf: ["responsive"],
        animation: ["responsive"],
        appearance: ["responsive"],
        backdropBlur: ["responsive"],
        backdropBrightness: ["responsive"],
        backdropContrast: ["responsive"],
        backdropDropShadow: ["responsive"],
        backdropFilter: ["responsive"],
        backdropGrayscale: ["responsive"],
        backdropHueRotate: ["responsive"],
        backdropInvert: ["responsive"],
        backdropSaturate: ["responsive"],
        backdropSepia: ["responsive"],
        backgroundAttachment: ["responsive"],
        backgroundBlendMode: ["responsive"],
        backgroundClip: ["responsive"],
        backgroundColor: ["responsive", "dark", "group-hover", "focus-within", "hover", "focus", "checked"],
        backgroundImage: ["responsive"],
        backgroundOpacity: ["responsive", "dark", "group-hover", "focus-within", "hover", "focus"],
        backgroundPosition: ["responsive"],
        backgroundRepeat: ["responsive"],
        backgroundSize: ["responsive"],
        blur: ["responsive"],
        borderCollapse: ["responsive"],
        borderColor: ["responsive", "dark", "group-hover", "focus-within", "hover", "focus", "checked", "disabled"],
        borderOpacity: ["responsive", "dark", "group-hover", "focus-within", "hover", "focus"],
        borderRadius: ["responsive"],
        borderStyle: ["responsive"],
        borderWidth: ["responsive", "hover"],
        boxDecorationBreak: ["responsive"],
        boxShadow: ["responsive", "group-hover", "focus-within", "hover", "focus"],
        boxSizing: ["responsive"],
        brightness: ["responsive"],
        clear: ["responsive"],
        container: ["responsive"],
        contrast: ["responsive"],
        cursor: ["responsive", "disabled"],
        display: ["responsive", "disabled"],
        divideColor: ["responsive", "dark"],
        divideOpacity: ["responsive", "dark"],
        divideStyle: ["responsive"],
        divideWidth: ["responsive"],
        dropShadow: ["responsive"],
        fill: ["responsive"],
        filter: ["responsive"],
        flex: ["responsive"],
        flexDirection: ["responsive"],
        flexGrow: ["responsive"],
        flexShrink: ["responsive"],
        flexWrap: ["responsive"],
        float: ["responsive"],
        fontFamily: ["responsive"],
        fontSize: ["responsive"],
        fontSmoothing: ["responsive"],
        fontStyle: ["responsive"],
        fontVariantNumeric: ["responsive"],
        fontWeight: ["responsive"],
        gap: ["responsive"],
        gradientColorStops: ["responsive", "dark", "hover", "focus", "disabled"],
        grayscale: ["responsive"],
        gridAutoColumns: ["responsive"],
        gridAutoFlow: ["responsive"],
        gridAutoRows: ["responsive"],
        gridColumn: ["responsive"],
        gridColumnEnd: ["responsive"],
        gridColumnStart: ["responsive"],
        gridRow: ["responsive"],
        gridRowEnd: ["responsive"],
        gridRowStart: ["responsive"],
        gridTemplateColumns: ["responsive"],
        gridTemplateRows: ["responsive"],
        height: ["responsive", "hover"],
        hueRotate: ["responsive"],
        inset: ["responsive"],
        invert: ["responsive"],
        isolation: ["responsive"],
        justifyContent: ["responsive"],
        justifyItems: ["responsive"],
        justifySelf: ["responsive"],
        letterSpacing: ["responsive"],
        lineHeight: ["responsive"],
        listStylePosition: ["responsive"],
        listStyleType: ["responsive"],
        margin: ["responsive"],
        maxHeight: ["responsive"],
        maxWidth: ["responsive"],
        minHeight: ["responsive"],
        minWidth: ["responsive"],
        mixBlendMode: ["responsive"],
        objectFit: ["responsive"],
        objectPosition: ["responsive"],
        opacity: ["responsive", "group-hover", "focus-within", "hover", "focus", "disabled"],
        order: ["responsive"],
        outline: ["responsive", "focus-within", "focus"],
        overflow: ["responsive"],
        overscrollBehavior: ["responsive"],
        padding: ["responsive"],
        placeContent: ["responsive"],
        placeItems: ["responsive"],
        placeSelf: ["responsive"],
        placeholderColor: ["responsive", "dark", "focus"],
        placeholderOpacity: ["responsive", "dark", "focus"],
        pointerEvents: ["responsive"],
        position: ["responsive"],
        resize: ["responsive"],
        ringColor: ["responsive", "dark", "focus-within", "focus"],
        ringOffsetColor: ["responsive", "dark", "focus-within", "focus"],
        ringOffsetWidth: ["responsive", "focus-within", "focus"],
        ringOpacity: ["responsive", "dark", "focus-within", "focus"],
        ringWidth: ["responsive", "focus-within", "focus"],
        rotate: ["responsive", "hover", "focus"],
        saturate: ["responsive"],
        scale: ["responsive", "hover", "focus"],
        sepia: ["responsive"],
        skew: ["responsive", "hover", "focus"],
        space: ["responsive"],
        stroke: ["responsive"],
        strokeWidth: ["responsive"],
        tableLayout: ["responsive"],
        textAlign: ["responsive"],
        textColor: ["responsive", "dark", "group-hover", "focus-within", "hover", "focus", "disabled"],
        textDecoration: ["responsive", "group-hover", "focus-within", "hover", "focus"],
        textOpacity: ["responsive", "dark", "group-hover", "focus-within", "hover", "focus", "disabled"],
        textOverflow: ["responsive"],
        textTransform: ["responsive"],
        transform: ["responsive"],
        transformOrigin: ["responsive"],
        transitionDelay: ["responsive"],
        transitionDuration: ["responsive"],
        transitionProperty: ["responsive"],
        transitionTimingFunction: ["responsive"],
        translate: ["responsive", "hover", "focus"],
        userSelect: ["responsive"],
        verticalAlign: ["responsive"],
        visibility: ["responsive"],
        whitespace: ["responsive"],
        width: ["responsive"],
        wordBreak: ["responsive"],
        zIndex: ["responsive", "focus-within", "focus"],
        extend: {
            cursor: ["disabled"],
            textOpacity: ["disabled"],
            textColor: ["disabled"],
            textDecoration: ["focus-visible"],
            boxDecorationBreak: ["hover", "focus"],
            borderColor: ["checked"],
            borderWidth: ["last"],
            backgroundColor: ["odd", "even", "checked"],
        },
    },
    plugins: [],
};
